<br />
<br />

<form method="POST">
    <label for="code">Code</label>
    <input id="code" name="code" type="text"><br />

    <label for="fullname">Fullname</label>
    <input id="fullname" name="fullname" type="text"><br />

    <label for="age">Age</label>
    <input id="age" name="age" type="number"><br />

    <label for="work">Work</label>
    <input id="work" name="work" type="text"><br />

    <label for="zp">Zp</label>
    <input id="zp" name="zp" type="number"><br />

    <label for="kids">Kids</label>
    <input id="kids" name="kids" type="number"><br />

    <button type="submit">Add</button>
</form>